### ISSUE TITLE
Cannot create symlink to '../bin/busybox': Read-only file system

### ISSUE THREAD

**Issue by techtoys** [OpenNuvoton/N32926_Linux_BSP#1]
Hi

I tried to unzip the file with `tar zxvf rootfs-2.6.35.tar.gz`. The host is a Virtualbox running Ubuntu 12.04LTS, a shared folder between Windows 7 and Ubuntu created as D:/vmshare.

After $ git clone there is now D:/vmshare/N32926_Linux_BSP. 

In terminal I have 
`root@tizen: /media/sf_vmshare/N32926_Linux_BSP$`

When I typed `tar zxvf rootfs-2.6.35.tar.gz` the operation can be initi until this error message shown :+1: 
Cannot create symlink to '../bin/busybox': Read-only file system.

Previously I thought it was due to ownership of file so I did chmod -R 770 for that rootfs-2.6.35.tar.gz but it turned out the same error came out.

How to solve this problem?>

John

**Comment by techtoys** [comment]
Follow up: By googling the problem `Cannot create symlink` I was able to solve it from this [link](https://blog.csdn.net/ganshuyu/article/details/44565157). Unfortunately, after having solved this there is another problem as:

(1) tar : rootfs-2.6.35/dev/console: Cannot mknod: Operation not permitted

Not expect to be so difficult with simple procedure like tar.

**Comment by cyliangtw** [comment]
In  Ubuntu, it's permission matter, please follow the below command:
`$ sudo tar zxvf rootfs-2.6.35.tar.gz`

**Comment by techtoys** [comment]
cy

I tried $ sudo as well but it cannot solve the problem. It is still `tar : rootfs-2.6.35/dev/console: Cannot mknod: Operation not permitted`

John

**Comment by cyliangtw** [comment]
My environment is the same, Ubuntu 12.x:
`Welcome to Ubuntu 12.04.4 LTS (GNU/Linux 3.11.0-19-generic x86_64)`

You could ensure your permission by manual, like as:
```
chris@MS00-Linux:dev$ mknod -m 600 console02 c 5 1
mknod: `console02': Permission denied
chris@MS00-Linux:dev$ sudo mknod -m 600 console02 c 5 1
chris@MS00-Linux:dev$ ls
console  console02
chris@MS00-Linux:dev$

```

**Comment by techtoys** [comment]
I tried 
```
mknod -m 600 rootfs-2.6.35.tar.gz
```
Response is:
```
mknod: 'rootfs-2.6.35.tar.gz'  : File exists
```

Then I tried again `$ sudo tar zxvf rootfs-2.6.35.tar.gz`, now it says:
```
...
rootfs-2.6.35/dev/
rootfs-2.6.35/dev/console
tar: rootfs-2.6.35/dev/console: Cannot mknod: Operation not permitted
...
rootfs-2.6.35/var
...
tar: Exiting with failure status due to previous errors
```

Not all files cannot tar. It is only the /dev/console have problem, and at the end it feedback `tar: Exiting with failure status due to previous errors`

**Comment by cyliangtw** [comment]
Please ensure your permission on mknod at first.
If you can't make any node by below command, it must be permission issue and you should check it with your Linux administrator or get help from google search.
`$ sudo mknod -m 600 console02 c 5 1`

**Comment by techtoys** [comment]
All problems stem from the shared folder between Windows host and Ubuntu emulated in VirtualBox. When I switched to a newly created folder in ~/work, all operations became fine, and image build also OK now.

Thanks.
